### PR TITLE
Fix Access-Control-Allow-Origin with wildcard

### PR DESCRIPTION
**Pull request by gonzaloserrano**
Hi,

I want to return the wildcard in the `Access-Control-Allow-Origin` response header and tried this quick fix.

Does it make sense to you?

Thanks

### CODE REVIEW

**Comment by cdent** [comment]
I came here looking for exactly this fix, from reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin and https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null

Any chance this might get merged?

**Comment by cdent** [comment]
Hmmm. I see what it's doing: sending as origin, the current origin. This isn't ideal for strange cache and proxy scenarios.

**Comment by pkieltyka** [comment]
Resolved in https://github.com/go-chi/cors/commit/b978ea830f7c8f371fd43358b5665e7047691207

**Comment by gonzaloserrano** [comment]
Thank you!

**Pull request closed without merging**
